apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gelco-distribucion-service
  name: gelco-distribucion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gelco-distribucion-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: gelco-distribucion-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://gelco-discovery:8761/eureka/
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://gelco-config:8888
          image: gelco-distribucion-service
          name: gelco-distribucion-service
          ports:
            - containerPort: 8087
              protocol: TCP
      restartPolicy: Always
