server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/gelco_catalogo
    username: postgres
    password: pgVGAPvwoGKBoMeLxZYGmqkZcIJZwnfi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000