server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://gelco-db-postgres:5432/gelco_devoluciones
    username: gelco_admin
    password: gelco2026*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000